# Yurii Rubel workflow
name: .Net/C#
on:
  #trigger on the push event
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # ability to run the script in manual mode
  workflow_dispatch:
jobs:
  build:
    # operating system
    runs-on: windows-latest
    strategy:
      matrix:
         configuration: [Debug, Release]
    env:
      Solution_Name: Products.sln                         
      Test_Project_Path: Products.csproj                
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    # software
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # download dependencies
    - name: Restore Dependencies
      run: dotnet restore
    # project build 
    - name: Build Project
      run: dotnet build --configuration Release --no-restore
    # unit tests
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal
